{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "feaa6c47_c0510664",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 35
      },
      "lineNbr": 0,
      "author": {
        "id": 1000153
      },
      "writtenOn": "2022-02-04T19:35:08Z",
      "side": 1,
      "message": "FYI, CI failure was likely a false positive.  We had a breaking change in boost URI, and this got caught in the crossfire.  I rebased it, and the rebase should give a better result.",
      "revId": "04d834806821a7036fe06ad5f8a28544db18ce29",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}