{
  "comments": [
    {
      "key": {
        "uuid": "a5e96a4c_b57ddc20",
        "filename": "http/http_client.hpp",
        "patchSetId": 5
      },
      "lineNbr": 289,
      "author": {
        "id": 1000168
      },
      "writtenOn": "2020-06-22T17:29:19Z",
      "side": 1,
      "message": "Clarification: What\u0027s the reason behind this? What we are trying to do here, after the connection is closed?",
      "range": {
        "startLine": 289,
        "startChar": 8,
        "endLine": 289,
        "endChar": 21
      },
      "revId": "3ed10b3eb4fee48904357c0c2f0ea6ea0f9bbb93",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "247b7177_0c446fea",
        "filename": "http/http_client.hpp",
        "patchSetId": 5
      },
      "lineNbr": 289,
      "author": {
        "id": 1000269
      },
      "writtenOn": "2020-06-23T19:06:01Z",
      "side": 1,
      "message": "CheckQueue function is single place where we handles all the retry or terminate actions related support. doClose will get called when there is failure in send/receive. At that time, we will close existing connection and re-open connection (inside checkQueue()) after configured timeout interval, depending on retry count and terminate actions.",
      "parentUuid": "a5e96a4c_b57ddc20",
      "range": {
        "startLine": 289,
        "startChar": 8,
        "endLine": 289,
        "endChar": 21
      },
      "revId": "3ed10b3eb4fee48904357c0c2f0ea6ea0f9bbb93",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "a648d699_f977056f",
        "filename": "http/http_client.hpp",
        "patchSetId": 5
      },
      "lineNbr": 289,
      "author": {
        "id": 1000168
      },
      "writtenOn": "2020-06-24T02:06:42Z",
      "side": 1,
      "message": "Please change the function name then doClose() seems confusing as it indicates we are stopping the connection.\ncloseAndRecheckQueue() ?",
      "parentUuid": "247b7177_0c446fea",
      "range": {
        "startLine": 289,
        "startChar": 8,
        "endLine": 289,
        "endChar": 21
      },
      "revId": "3ed10b3eb4fee48904357c0c2f0ea6ea0f9bbb93",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "9c1717f7_313cc930",
        "filename": "http/http_client.hpp",
        "patchSetId": 5
      },
      "lineNbr": 289,
      "author": {
        "id": 1000269
      },
      "writtenOn": "2020-06-24T10:50:58Z",
      "side": 1,
      "message": "Since actual business logic of retries are done in checkQueue, In all other functions also we are doing required operations(Connect, close, send, Recv etc..) and leaving control to checkQueue. So i think we are good here.",
      "parentUuid": "a648d699_f977056f",
      "range": {
        "startLine": 289,
        "startChar": 8,
        "endLine": 289,
        "endChar": 21
      },
      "revId": "3ed10b3eb4fee48904357c0c2f0ea6ea0f9bbb93",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "a4cf3130_2004daa6",
        "filename": "http/http_client.hpp",
        "patchSetId": 5
      },
      "lineNbr": 289,
      "author": {
        "id": 1000168
      },
      "writtenOn": "2020-06-24T13:30:49Z",
      "side": 1,
      "message": "You meant to say doClose() function name conveys what is done inside the function.\n\nSay when there is failure, we call doClose() (any reader will assume that it is closing the connection), but in reality it is not, it may re-open based on the need.",
      "parentUuid": "9c1717f7_313cc930",
      "range": {
        "startLine": 289,
        "startChar": 8,
        "endLine": 289,
        "endChar": 21
      },
      "revId": "3ed10b3eb4fee48904357c0c2f0ea6ea0f9bbb93",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    }
  ]
}