{
  "comments": [
    {
      "key": {
        "uuid": "c7096c36_8137ec13",
        "filename": "redfish-core/lib/update_service.hpp",
        "patchSetId": 52
      },
      "lineNbr": 400,
      "author": {
        "id": 1001049
      },
      "writtenOn": "2021-08-31T16:30:18Z",
      "side": 1,
      "message": "nit:\nCould be written as below, so that we consider the error condition in write operation too.\n\nout \u003c\u003c body;\nif(out.bad())\n{\n   return false;\n}\n\nwrite function of std::ofstream already has a check for .bad so we can directly call line 400 after line 395.",
      "range": {
        "startLine": 396,
        "startChar": 4,
        "endLine": 400,
        "endChar": 16
      },
      "revId": "ed11966108f433054b390ea2fa13eb9a719543d1",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "5e4de654_7a9b1edb",
        "filename": "redfish-core/lib/update_service.hpp",
        "patchSetId": 52
      },
      "lineNbr": 751,
      "author": {
        "id": 1001049
      },
      "writtenOn": "2021-08-31T16:30:18Z",
      "side": 1,
      "message": "nit:\nWhy are we not returning at first error?",
      "range": {
        "startLine": 751,
        "startChar": 24,
        "endLine": 751,
        "endChar": 33
      },
      "revId": "ed11966108f433054b390ea2fa13eb9a719543d1",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    }
  ]
}